### ISSUE TITLE
Test for changing everything needed

### ISSUE THREAD

**Issue by tumb1er** [just-work/django-admin-smoke#19]
Need a test to check that all desired fields could be changed via admin.

It may look like this:
```
def test_change_fields(self):
     r = self.client.get(self.change_url)
     data = self.get_form_data_from_response(r)
     changes = self.change_fields(data)
     data.update(changes)
     r = self.client.post(url, data=data)
     obj = self.get_object()
     for k, v in changes.items():
        self.assertEqual(getattr(obj, k), v)
def change_fields(data: dict) -> dict:
    raise NotImplementedError()
````

**Comment by tumb1er** [comment]
https://travis-ci.org/github/just-work/django-admin-blame/jobs/674282585

```
======================================================================
ERROR: setUpClass (admin_smoke.tests.AdminTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/django/test/testcases.py", line 1137, in setUpClass
    cls.setUpTestData()
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/admin_smoke/tests.py", line 44, in setUpTestData
    cls.admin = cls.model_admin(cls.model, site)
AttributeError: type object 'AdminTests' has no attribute 'model_admin'
```

AdminTests mixin is now discovered as a test case, it's a bug.

```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/admin_smoke/tests.py", line 286, in test_all_fields_present
    f'fields {list(absent_fields)} are absent on form.')
AssertionError: {'modified', 'modified_by', 'created', 'created_by'} is not false : fields ['modified', 'modified_by', 'created', 'created_by'] are absent on form.
```

These fields are marked in model as non-editable, this should be considered as valid behavior.
